# Generated by Django 5.1 on 2025-05-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
